"""add pipeline_run table

Revision ID: 5a6734c8a5c8
Revises: 7186a58b67e9
Create Date: 2026-07-26 17:54:49.565564
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '5a6734c8a5c8'
down_revision: str | None = '7186a58b67e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('idle', 'running', 'done', 'error', name='pipelinerunstatus', native_enum=False, length=16), nullable=False),
    sa.Column('current_stage', sa.Enum('ingest', 'parse', 'extract', 'embed', 'timeline', 'phases', 'graph', 'direction', 'gaps', 'view', 'report', name='stage', native_enum=False, length=16), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_pipeline_run_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_run'))
    )
    op.create_index('ix_pipeline_run_one_running_per_project', 'pipeline_run', ['project_id'], unique=True, postgresql_where=sa.text("status = 'running'"))
    op.create_index(op.f('ix_pipeline_run_project_id'), 'pipeline_run', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_run_project_id'), table_name='pipeline_run')
    op.drop_index('ix_pipeline_run_one_running_per_project', table_name='pipeline_run', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('pipeline_run')
    # ### end Alembic commands ###
