"""scope entities to project

Revision ID: c9304a50d980
Revises: 0ffe0074bac8
Create Date: 2026-07-24 15:56:26.946623
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'c9304a50d980'
down_revision: str | None = '0ffe0074bac8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('project_id', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('entity_type_value'), 'entities', type_='unique')
    op.create_unique_constraint('entity_project_type_value', 'entities', ['project_id', 'type', 'normalized_value'])
    op.create_index(op.f('ix_entities_project_id'), 'entities', ['project_id'], unique=False)
    op.create_foreign_key(op.f('fk_entities_project_id_projects'), 'entities', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_entities_project_id_projects'), 'entities', type_='foreignkey')
    op.drop_index(op.f('ix_entities_project_id'), table_name='entities')
    op.drop_constraint('entity_project_type_value', 'entities', type_='unique')
    op.create_unique_constraint(op.f('entity_type_value'), 'entities', ['type', 'normalized_value'], postgresql_nulls_not_distinct=False)
    op.drop_column('entities', 'project_id')
    # ### end Alembic commands ###
