"""initial schema

Revision ID: 0ffe0074bac8
Revises: 
Create Date: 2026-07-24 10:39:43.601805
"""
from __future__ import annotations

from collections.abc import Sequence

import fastapi_users_db_sqlalchemy
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '0ffe0074bac8'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any Vector column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('decision_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor', sa.Enum('system', 'user', name='auditactor', native_enum=False, length=8), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_audit'))
    )
    op.create_index(op.f('ix_decision_audit_decision_type'), 'decision_audit', ['decision_type'], unique=False)
    op.create_index(op.f('ix_decision_audit_target_id'), 'decision_audit', ['target_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('person', 'group', 'tool', 'cost', 'experiment', 'hypothesis', 'citation', name='entitytype', native_enum=False, length=16), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities')),
    sa.UniqueConstraint('type', 'normalized_value', name='entity_type_value')
    )
    op.create_table('phase_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('phase_name', sa.String(length=128), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phase_templates')),
    sa.UniqueConstraint('domain', 'ordinal', name='phase_template_domain_ordinal')
    )
    op.create_index(op.f('ix_phase_templates_domain'), 'phase_templates', ['domain'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('current_path', sa.Text(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('fs_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fs_modified', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_state', sa.Enum('pending', 'parsed', 'extracted', 'embedded', 'analyzed', 'error', name='processingstate', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_artifacts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('project_id', 'content_hash', name='artifact_project_hash')
    )
    op.create_index(op.f('ix_artifacts_content_hash'), 'artifacts', ['content_hash'], unique=False)
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_table('direction_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('inferred_direction_summary', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_direction_snapshots_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direction_snapshots'))
    )
    op.create_index(op.f('ix_direction_snapshots_project_id'), 'direction_snapshots', ['project_id'], unique=False)
    op.create_table('domain_classification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('domain', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_domain_classification_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_domain_classification'))
    )
    op.create_index(op.f('ix_domain_classification_project_id'), 'domain_classification', ['project_id'], unique=True)
    op.create_table('gaps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('structural', 'promised_unfulfilled', name='gaptype', native_enum=False, length=24), nullable=False),
    sa.Column('phase_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('open', 'confirmed', 'dismissed', 'resolved', name='gapstatus', native_enum=False, length=16), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['phase_templates.id'], name=op.f('fk_gaps_phase_id_phase_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_gaps_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gaps'))
    )
    op.create_index(op.f('ix_gaps_project_id'), 'gaps', ['project_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_table('artifact_content',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('embedded_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parser_name', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_content_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_content'))
    )
    op.create_index(op.f('ix_artifact_content_artifact_id'), 'artifact_content', ['artifact_id'], unique=True)
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_chunks_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chunks'))
    )
    op.create_index(op.f('ix_chunks_artifact_id'), 'chunks', ['artifact_id'], unique=False)
    op.create_table('direction_labels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Enum('current', 'superseded', 'unclear', name='directionlabelvalue', native_enum=False, length=16), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('signal_a_score', sa.Float(), nullable=True),
    sa.Column('signal_b_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_direction_labels_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_direction_labels'))
    )
    op.create_index(op.f('ix_direction_labels_artifact_id'), 'direction_labels', ['artifact_id'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('span', sa.String(length=64), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extractor', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_entity_mentions_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_entity_mentions_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_mentions'))
    )
    op.create_index(op.f('ix_entity_mentions_artifact_id'), 'entity_mentions', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_entity_id'), 'entity_mentions', ['entity_id'], unique=False)
    op.create_table('phase_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('phase_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('auto', 'human', name='assignmentsource', native_enum=False, length=8), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_phase_assignments_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phase_id'], ['phase_templates.id'], name=op.f('fk_phase_assignments_phase_id_phase_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phase_assignments'))
    )
    op.create_index(op.f('ix_phase_assignments_artifact_id'), 'phase_assignments', ['artifact_id'], unique=False)
    op.create_table('relationship_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('src_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('dst_artifact_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('references', 'builds_on', 'mentioned_by', name='edgetype', native_enum=False, length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dst_artifact_id'], ['artifacts.id'], name=op.f('fk_relationship_edges_dst_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_artifact_id'], ['artifacts.id'], name=op.f('fk_relationship_edges_src_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_edges'))
    )
    op.create_index(op.f('ix_relationship_edges_dst_artifact_id'), 'relationship_edges', ['dst_artifact_id'], unique=False)
    op.create_index(op.f('ix_relationship_edges_src_artifact_id'), 'relationship_edges', ['src_artifact_id'], unique=False)
    op.create_table('resolved_dates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_source', sa.Enum('content', 'doc_meta', 'filesystem', name='datesignalsource', native_enum=False, length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('extractor', sa.String(length=64), nullable=False),
    sa.Column('is_chosen', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_resolved_dates_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resolved_dates'))
    )
    op.create_index(op.f('ix_resolved_dates_artifact_id'), 'resolved_dates', ['artifact_id'], unique=False)
    op.create_table('stage_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Enum('ingest', 'parse', 'extract', 'embed', 'timeline', 'phases', 'direction', 'gaps', 'view', 'report', name='stage', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'error', name='stagestatus', native_enum=False, length=16), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("input_hash <> ''", name=op.f('ck_stage_state_input_hash_nonempty')),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_stage_state_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage_state')),
    sa.UniqueConstraint('artifact_id', 'stage', name='stage_state_artifact_stage')
    )
    op.create_index(op.f('ix_stage_state_artifact_id'), 'stage_state', ['artifact_id'], unique=False)
    op.create_table('structured_tables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('table_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rows', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_structured_tables_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_structured_tables'))
    )
    op.create_index(op.f('ix_structured_tables_artifact_id'), 'structured_tables', ['artifact_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_timeline_events_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_timeline_events_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    op.create_index(op.f('ix_timeline_events_project_id'), 'timeline_events', ['project_id'], unique=False)
    op.create_table('view_projection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('suggested_name', sa.Text(), nullable=True),
    sa.Column('suggested_category', sa.String(length=128), nullable=True),
    sa.Column('virtual_path', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_view_projection_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['view_projection.id'], name=op.f('fk_view_projection_superseded_by_view_projection'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_view_projection'))
    )
    op.create_index(op.f('ix_view_projection_artifact_id'), 'view_projection', ['artifact_id'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('artifact_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.Enum('chunk', 'doc', name='embeddinglevel', native_enum=False, length=8), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_embeddings_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], name=op.f('fk_embeddings_chunk_id_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings'))
    )
    op.create_index(op.f('ix_embeddings_artifact_id'), 'embeddings', ['artifact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_artifact_id'), table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_view_projection_artifact_id'), table_name='view_projection')
    op.drop_table('view_projection')
    op.drop_index(op.f('ix_timeline_events_project_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_structured_tables_artifact_id'), table_name='structured_tables')
    op.drop_table('structured_tables')
    op.drop_index(op.f('ix_stage_state_artifact_id'), table_name='stage_state')
    op.drop_table('stage_state')
    op.drop_index(op.f('ix_resolved_dates_artifact_id'), table_name='resolved_dates')
    op.drop_table('resolved_dates')
    op.drop_index(op.f('ix_relationship_edges_src_artifact_id'), table_name='relationship_edges')
    op.drop_index(op.f('ix_relationship_edges_dst_artifact_id'), table_name='relationship_edges')
    op.drop_table('relationship_edges')
    op.drop_index(op.f('ix_phase_assignments_artifact_id'), table_name='phase_assignments')
    op.drop_table('phase_assignments')
    op.drop_index(op.f('ix_entity_mentions_entity_id'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_artifact_id'), table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_index(op.f('ix_direction_labels_artifact_id'), table_name='direction_labels')
    op.drop_table('direction_labels')
    op.drop_index(op.f('ix_chunks_artifact_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_artifact_content_artifact_id'), table_name='artifact_content')
    op.drop_table('artifact_content')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_gaps_project_id'), table_name='gaps')
    op.drop_table('gaps')
    op.drop_index(op.f('ix_domain_classification_project_id'), table_name='domain_classification')
    op.drop_table('domain_classification')
    op.drop_index(op.f('ix_direction_snapshots_project_id'), table_name='direction_snapshots')
    op.drop_table('direction_snapshots')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_content_hash'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_phase_templates_domain'), table_name='phase_templates')
    op.drop_table('phase_templates')
    op.drop_table('entities')
    op.drop_index(op.f('ix_decision_audit_target_id'), table_name='decision_audit')
    op.drop_index(op.f('ix_decision_audit_decision_type'), table_name='decision_audit')
    op.drop_table('decision_audit')
    # ### end Alembic commands ###
