"""add corpus fingerprint hash to domain classification

Revision ID: 76dd7b9fa073
Revises: c9304a50d980
Create Date: 2026-07-25 17:55:59.808069
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '76dd7b9fa073'
down_revision: str | None = 'c9304a50d980'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain_classification', sa.Column('corpus_fingerprint_hash', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domain_classification', 'corpus_fingerprint_hash')
    # ### end Alembic commands ###
