"""add sections and corpus fingerprint hash to reports

Revision ID: 7186a58b67e9
Revises: 13091b6e1eaf
Create Date: 2026-07-26 16:59:30.889638
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '7186a58b67e9'
down_revision: str | None = '13091b6e1eaf'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('reports', sa.Column('corpus_fingerprint_hash', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'corpus_fingerprint_hash')
    op.drop_column('reports', 'sections')
    # ### end Alembic commands ###
