"""direction snapshot fingerprint and direction label unique artifact

Revision ID: cf26d670cf4f
Revises: 76dd7b9fa073
Create Date: 2026-07-26 00:36:03.700110
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'cf26d670cf4f'
down_revision: str | None = '76dd7b9fa073'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_direction_labels_artifact_id'), table_name='direction_labels')
    op.create_index(op.f('ix_direction_labels_artifact_id'), 'direction_labels', ['artifact_id'], unique=True)
    op.add_column('direction_snapshots', sa.Column('corpus_fingerprint_hash', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direction_snapshots', 'corpus_fingerprint_hash')
    op.drop_index(op.f('ix_direction_labels_artifact_id'), table_name='direction_labels')
    op.create_index(op.f('ix_direction_labels_artifact_id'), 'direction_labels', ['artifact_id'], unique=False)
    # ### end Alembic commands ###
