"""add source to view_projection

Revision ID: 13091b6e1eaf
Revises: cf26d670cf4f
Create Date: 2026-07-26 13:28:11.750504
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '13091b6e1eaf'
down_revision: str | None = 'cf26d670cf4f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('view_projection', sa.Column('source', sa.Enum('auto', 'human', name='assignmentsource', native_enum=False, length=8), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('view_projection', 'source')
    # ### end Alembic commands ###
